services:
    Andreo\EventSauce\Doctrine\Migration\EventMessageSchemaBuilder: '@Andreo\EventSauce\Doctrine\Migration\DefaultEventMessageSchemaBuilder'
    Andreo\EventSauce\Doctrine\Migration\OutboxMessageSchemaBuilder: '@Andreo\EventSauce\Doctrine\Migration\DefaultOutboxMessageSchemaBuilder'
    Andreo\EventSauce\Doctrine\Migration\SnapshotSchemaBuilder: '@Andreo\EventSauce\Doctrine\Migration\DefaultSnapshotSchemaBuilder'

    Andreo\EventSauce\Doctrine\Migration\DefaultEventMessageSchemaBuilder:
        arguments:
            $tableSchema: '@EventSauce\MessageRepository\TableSchema\TableSchema'
        lazy: true

    Andreo\EventSauce\Doctrine\Migration\DefaultOutboxMessageSchemaBuilder:
        lazy: true

    Andreo\EventSauce\Doctrine\Migration\DefaultSnapshotSchemaBuilder:
        lazy: true

    Andreo\EventSauce\Doctrine\Migration\GenerateAggregateMigrationCommand:
        arguments:
            - '@doctrine.migrations.dependency_factory'
            - '@Andreo\EventSauce\Doctrine\Migration\TableNameSuffix'
            - '@Andreo\EventSauce\Doctrine\Migration\EventMessageSchemaBuilder'
            - '@Andreo\EventSauce\Doctrine\Migration\OutboxMessageSchemaBuilder'
            - '@Andreo\EventSauce\Doctrine\Migration\SnapshotSchemaBuilder'
        tags:
            - { name: console.command, command: andreo:event-sauce:doctrine:migration:generate }