parameters:
    andreo.event_sauce.outbox.back_off.initial_delay_ms: 100000
    andreo.event_sauce.outbox.back_off.max_tries: 25

services:
    EventSauce\BackOff\BackOffStrategy: '@EventSauce\BackOff\ExponentialBackOffStrategy'
    EventSauce\MessageOutbox\RelayCommitStrategy: '@EventSauce\MessageOutbox\MarkMessagesConsumedOnCommit'

    EventSauce\BackOff\ExponentialBackOffStrategy:
        class: EventSauce\BackOff\ExponentialBackOffStrategy
        public: false
        lazy: true
        arguments:
            - '%andreo.event_sauce.outbox.back_off.initial_delay_ms%'
            - '%andreo.event_sauce.outbox.back_off.max_tries%'

    EventSauce\BackOff\FibonacciBackOffStrategy:
        class: EventSauce\BackOff\FibonacciBackOffStrategy
        public: false
        lazy: true
        arguments:
            - '%andreo.event_sauce.outbox.back_off.initial_delay_ms%'
            - '%andreo.event_sauce.outbox.back_off.max_tries%'

    EventSauce\BackOff\LinearBackOffStrategy:
        class: EventSauce\BackOff\LinearBackOffStrategy
        public: false
        lazy: true
        arguments:
            - '%andreo.event_sauce.outbox.back_off.initial_delay_ms%'
            - '%andreo.event_sauce.outbox.back_off.max_tries%'

    EventSauce\BackOff\NoWaitingBackOffStrategy:
        class: EventSauce\BackOff\NoWaitingBackOffStrategy
        public: false
        lazy: true
        arguments:
            - '%andreo.event_sauce.outbox.back_off.max_tries%'

    EventSauce\BackOff\ImmediatelyFailingBackOffStrategy:
        class: EventSauce\BackOff\ImmediatelyFailingBackOffStrategy
        public: false
        lazy: true

    EventSauce\MessageOutbox\MarkMessagesConsumedOnCommit:
        class: EventSauce\MessageOutbox\MarkMessagesConsumedOnCommit
        public: false
        lazy: true

    EventSauce\MessageOutbox\DeleteMessageOnCommit:
        class: EventSauce\MessageOutbox\DeleteMessageOnCommit
        public: false
        lazy: true

    Andreo\EventSauce\Outbox\OutboxProcessMessagesCommand:
        public: false
        arguments:
            - !tagged_iterator { tag: 'andreo.event_sauce.outbox_relay', index_by: 'name' }
            - !service
                class: Psr\Log\NullLogger
        tags:
            - { name: console.command, command: andreo:event-sauce:outbox-process-messages }
