services:
    Andreo\EventSauce\Serialization\SymfonySerializerFactory: '@Andreo\EventSauce\Serialization\DefaultSymfonySerializerFactory'

    andreo.event_sauce.symfony_serializer:
        class: Symfony\Component\Serializer\SerializerInterface
        public: false
        factory: ['@Andreo\EventSauce\Serialization\SymfonySerializerFactory', 'create']
        arguments:
            - !tagged_iterator andreo.event_sauce.symfony_serializer.normalizer
            - !tagged_iterator andreo.event_sauce.symfony_serializer.encoder

    Andreo\EventSauce\Serialization\DefaultSymfonySerializerFactory:
        public: false

    Symfony\Component\Serializer\Encoder\JsonEncoder:
        public: false
        tags:
            - { name: andreo.event_sauce.symfony_serializer.encoder }

    Symfony\Component\Serializer\Normalizer\PropertyNormalizer:
        public: false
        lazy: true
        tags:
            - { name: andreo.event_sauce.symfony_serializer.normalizer, priority: 100}

    Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
        public: false
        lazy: true
        tags:
            - { name: andreo.event_sauce.symfony_serializer.normalizer, priority: 90}

    Symfony\Component\Serializer\Normalizer\ArrayDenormalizer:
        public: false
        lazy: true
        tags:
            - { name: andreo.event_sauce.symfony_serializer.normalizer, priority: 80}

    Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor:
        public: false

    Symfony\Component\PropertyInfo\Extractor\ConstructorExtractor:
        public: false
        arguments:
            -
                - '@Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor'

    Symfony\Component\PropertyInfo\PropertyInfoExtractor:
        public: false
        arguments:
            - []
            -
                - '@Symfony\Component\PropertyInfo\Extractor\ConstructorExtractor'
                - '@Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor'

    Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
        public: false
        arguments:
            - null
            - null
            - null
            - '@Symfony\Component\PropertyInfo\PropertyInfoExtractor'
        tags:
            - { name: andreo.event_sauce.symfony_serializer.normalizer, priority: 0 }

    Andreo\EventSauce\Serialization\SymfonyPayloadSerializer:
        class: Andreo\EventSauce\Serialization\SymfonyPayloadSerializer
        public: false
        arguments:
            - '@andreo.event_sauce.symfony_serializer'