services:
    andreo.event_sauce.symfony_serializer:
        class: Symfony\Component\Serializer\SerializerInterface
        factory: [!service { class: Andreo\EventSauce\Serialization\SymfonySerializerFactory }, 'create' ]

    Andreo\EventSauce\Serialization\SymfonyPayloadSerializer:
        class: Andreo\EventSauce\Serialization\SymfonyPayloadSerializer
        public: false
        arguments:
            - '@andreo.event_sauce.symfony_serializer'